---
name: litmus-python-ci
on:
  pull_request:
    branches:
      - master    
  push:
    branches:
      - master
    tags-ignore:
      - '**'
defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checking syntax of shell script
        run: bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true

      - name: Installing and configuring dependencies
        run: make deps

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build Image
        run: make build
          
  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DNAME }}
          password: ${{ secrets.DPASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: uditgaurav/py-runner:ci
